CREATE TYPE "recording_status" AS ENUM ('UPLOADING', 'PROCESSING', 'READY', 'FAILED', 'DELETED');
CREATE TYPE "upload_session_status" AS ENUM ('PENDING', 'UPLOADING', 'COMPLETING', 'COMPLETED', 'ABORTED', 'EXPIRED');
CREATE TABLE "recordings" ("id" uuid PRIMARY KEY NOT NULL, "workspace_id" uuid NOT NULL, "owner_id" uuid NOT NULL, "title" text NOT NULL, "status" "recording_status" DEFAULT 'UPLOADING' NOT NULL, "source_object_key" text NOT NULL UNIQUE, "content_type" text NOT NULL, "size_bytes" bigint, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "upload_sessions" ("id" uuid PRIMARY KEY NOT NULL, "workspace_id" uuid NOT NULL, "recording_id" uuid NOT NULL REFERENCES "recordings"("id") ON DELETE CASCADE, "s3_upload_id" text NOT NULL UNIQUE, "object_key" text NOT NULL, "content_type" text NOT NULL, "part_size_bytes" integer NOT NULL, "expected_size_bytes" bigint NOT NULL, "max_part_count" integer NOT NULL, "status" "upload_session_status" DEFAULT 'PENDING' NOT NULL, "completion_idempotency_key_hash" text, "completion_request_hash" text, "completion_result" jsonb, "completion_started_at" timestamptz, "expires_at" timestamptz NOT NULL, "completed_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "upload_part_intents" ("upload_session_id" uuid NOT NULL REFERENCES "upload_sessions"("id") ON DELETE CASCADE, "part_number" integer NOT NULL, "content_length" bigint NOT NULL, "checksum_sha256" text NOT NULL, "is_final_part" boolean NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "upload_part_intents_pk" PRIMARY KEY("upload_session_id", "part_number"));
CREATE INDEX "recordings_workspace_created_idx" ON "recordings" ("workspace_id", "created_at");
CREATE INDEX "upload_sessions_workspace_status_idx" ON "upload_sessions" ("workspace_id", "status");
CREATE INDEX "upload_sessions_recording_idx" ON "upload_sessions" ("recording_id");
CREATE INDEX "upload_part_intents_session_idx" ON "upload_part_intents" ("upload_session_id", "part_number");
